// Do not edit this file directly. Edit the template instead: `./codegen/templates/mat.txt`.

import { Vec2 } from "./";

export class Mat2 {
	constructor(
		public xAxis: Vec2,
		public yAxis: Vec2,
	) {}

	/**
	 * Creates a new `Mat2` from multiple values.
	 */
	static new(m00: number, m01: number, m10: number, m11: number): Mat2 {
		return new Mat2(new Vec2(m00, m01), new Vec2(m10, m11));
	}

	/** All zeroes. (0, 0..) */
	static get ZERO() {
		return Mat2.fromCols(Vec2.ZERO, Vec2.ZERO);
	}

	/** All `Identity`, where all diagonal elements are `1`, and all off-diagonal elements are `0`. */
	static get IDENTITY() {
		return Mat2.fromCols(Vec2.X, Vec2.Y);
	}

	/** All `NaN`. (NaN, NaN..) */
	static get NAN() {
		return Mat2.fromCols(Vec2.NAN, Vec2.NAN);
	}

	/**
	 * Creates a 2x2 matrix from four column vectors.
	 */
	static fromCols(xAxis: Vec2, yAxis: Vec2): Mat2 {
		return new Mat2(xAxis, yAxis);
	}

	/**
	 * Creates a 2x2 matrix from four column vectors.
	 */
	static fromColsArray(m: number[]): Mat2 {
		return Mat2.new(m[0], m[1], m[2], m[3]);
	}

	/**
	 * Creates an array storing data in column major order.
	 */
	toColsArray(): number[] {
		return [this.xAxis.x, this.xAxis.y, this.yAxis.x, this.yAxis.y];
	}
}
