name: Build & Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1.1.1

      - name: bun install
        run: bun install

      - name: Build
        run: bun release

      - run: bun test --coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
